# Generated by Django 5.1.7 on 2025-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omWeb', '0002_produto_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ceo_words', models.TextField()),
                ('visao', models.TextField()),
                ('misao', models.TextField()),
                ('objectivo', models.TextField()),
                ('resposabilidade', models.TextField()),
                ('desc_social_network', models.TextField()),
                ('image_ceo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
