# Generated by Django 5.1.7 on 2025-03-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omWeb', '0003_om'),
    ]

    operations = [
        migrations.AddField(
            model_name='om',
            name='ceo',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
